/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Validacion;
import Conexion.ConexionLosCandiles;
import com.toedter.calendar.JDateChooser;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author JoseNvr
 */
public class ComprasMateriaPrima extends javax.swing.JFrame {
    
    //Declaración de variables para hacer la conexion a SQL
    ConexionLosCandiles con= new ConexionLosCandiles();
    CallableStatement cst;
    ResultSet r;
    Statement sentencia;

    DefaultTableModel comprasTableModel;

    
    //Declaracion para validar
    Validacion v= new Validacion();
    int cc=0;

    
    //Variable para determinar con que tipo se hara la busqueda
    int posicionFiltro;
    //Variable para la busqueda dinamica
    private TableRowSorter trsfiltro;
    //Formato de como retorna el string de la fecha
    SimpleDateFormat Formato = new SimpleDateFormat("yyyy-MM-dd");
    
    public ComprasMateriaPrima() {
        initComponents();
        
        ConexionLosCandiles con= new ConexionLosCandiles();
        
        
        cargarComprasGenerales();
        formatojTableDatosGeneralesCompras();
        
        this.setLocationRelativeTo(null);
        
        txtFechaCompraMP.setVisible(false);
        
        
        
        txtIDCompraMP.setText("CMP");
        txtIDProveedorCompra.setText("");
        txtIDProductoCompra.setText("");
        
        txtIDProductoCompra.setVisible(false);
        txtIDProveedorCompra.setVisible(false);
        
        txtNombreIngrediente.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCompras = new jcMousePanel.jcMousePanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        txtIDProveedorCompra = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnLimpiarCompraMP = new org.edisoncor.gui.button.ButtonColoredAction();
        jPanel27 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtIDCompraMP = new javax.swing.JTextField();
        txtIDProductoCompra = new javax.swing.JTextField();
        txtCantidadCompradaMP = new javax.swing.JTextField();
        txtFechaCompraMP = new javax.swing.JTextField();
        BtnAddMateriaPToCompra = new org.edisoncor.gui.button.ButtonTask();
        BtnAddCompraMP = new org.edisoncor.gui.button.ButtonTask();
        btnSeleccionarIngrediente = new org.edisoncor.gui.button.ButtonColoredAction();
        txtNombreIngrediente = new javax.swing.JTextField();
        txtNombreProveedorMP = new javax.swing.JTextField();
        btnSeleccionarProveedorMP = new org.edisoncor.gui.button.ButtonColoredAction();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnVolver = new org.edisoncor.gui.button.ButtonColoredAction();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaComprasGenerales = new javax.swing.JTable();
        jPanel26 = new javax.swing.JPanel();
        btnVerDetalleCompraMP = new org.edisoncor.gui.button.ButtonColoredAction();
        jPanel29 = new javax.swing.JPanel();
        BtnModificarIngredienteFromCompra = new org.edisoncor.gui.button.ButtonTask();
        BtnDeleteIngredienteFromCompra = new org.edisoncor.gui.button.ButtonTask();
        jPanel25 = new javax.swing.JPanel();
        searchFieldCompra = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        searchFilterCompra = new javax.swing.JComboBox<>();
        jPanel30 = new javax.swing.JPanel();
        BtnModificarDatosCompra = new org.edisoncor.gui.button.ButtonTask();
        BtnDeleteCompra = new org.edisoncor.gui.button.ButtonTask();
        jPanel21 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoEmpleados.jpg"))); // NOI18N

        jPanel19.setBackground(new java.awt.Color(255, 153, 51));
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel19MousePressed(evt);
            }
        });
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBackground(new java.awt.Color(255, 153, 51));
        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18))); // NOI18N
        jPanel23.setToolTipText("");
        jPanel23.setName(""); // NOI18N
        jPanel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel23MouseClicked(evt);
            }
        });
        jPanel23.setLayout(null);

        txtIDProveedorCompra.setBackground(new java.awt.Color(255, 204, 102));
        txtIDProveedorCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDProveedorCompraActionPerformed(evt);
            }
        });
        jPanel23.add(txtIDProveedorCompra);
        txtIDProveedorCompra.setBounds(860, 60, 100, 28);

        jPanel24.setBackground(new java.awt.Color(255, 204, 153));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Cantidad Comprada:");
        jPanel24.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 130, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Ingrediente: ");
        jPanel24.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 20));

        jPanel23.add(jPanel24);
        jPanel24.setBounds(420, 100, 130, 100);

        btnLimpiarCompraMP.setBackground(new java.awt.Color(204, 102, 0));
        btnLimpiarCompraMP.setText("Limpiar");
        btnLimpiarCompraMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCompraMPActionPerformed(evt);
            }
        });
        jPanel23.add(btnLimpiarCompraMP);
        btnLimpiarCompraMP.setBounds(820, 160, 116, 35);

        jPanel27.setBackground(new java.awt.Color(255, 204, 153));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Proveedor:");
        jPanel27.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 110, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("ID Compra:");
        jPanel27.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Fecha Compra:");
        jPanel27.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 20));

        jPanel23.add(jPanel27);
        jPanel27.setBounds(10, 100, 90, 100);

        txtIDCompraMP.setBackground(new java.awt.Color(255, 204, 102));
        txtIDCompraMP.setText("CMP");
        txtIDCompraMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCompraMPActionPerformed(evt);
            }
        });
        txtIDCompraMP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDCompraMPKeyTyped(evt);
            }
        });
        jPanel23.add(txtIDCompraMP);
        txtIDCompraMP.setBounds(110, 110, 100, 28);

        txtIDProductoCompra.setBackground(new java.awt.Color(255, 204, 102));
        txtIDProductoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDProductoCompraActionPerformed(evt);
            }
        });
        jPanel23.add(txtIDProductoCompra);
        txtIDProductoCompra.setBounds(860, 20, 100, 28);

        txtCantidadCompradaMP.setBackground(new java.awt.Color(255, 204, 102));
        txtCantidadCompradaMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadCompradaMPActionPerformed(evt);
            }
        });
        txtCantidadCompradaMP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadCompradaMPKeyTyped(evt);
            }
        });
        jPanel23.add(txtCantidadCompradaMP);
        txtCantidadCompradaMP.setBounds(560, 140, 90, 28);

        txtFechaCompraMP.setBackground(new java.awt.Color(255, 204, 102));
        txtFechaCompraMP.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtFechaCompraMP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaCompraMP.setText("aaaa/mm/dd");
        txtFechaCompraMP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaCompraMPFocusGained(evt);
            }
        });
        txtFechaCompraMP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaCompraMPKeyReleased(evt);
            }
        });
        jPanel23.add(txtFechaCompraMP);
        txtFechaCompraMP.setBounds(280, 170, 120, 29);

        BtnAddMateriaPToCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconAddMoreProducts.png"))); // NOI18N
        BtnAddMateriaPToCompra.setText("Añadir Ingrediente a la Compra");
        BtnAddMateriaPToCompra.setToolTipText("");
        BtnAddMateriaPToCompra.setDescription(" ");
        BtnAddMateriaPToCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddMateriaPToCompraActionPerformed(evt);
            }
        });
        jPanel23.add(BtnAddMateriaPToCompra);
        BtnAddMateriaPToCompra.setBounds(420, 40, 390, 50);

        BtnAddCompraMP.setBorder(null);
        BtnAddCompraMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconAddBuy.png"))); // NOI18N
        BtnAddCompraMP.setText("Registrar Compra");
        BtnAddCompraMP.setDescription(" ");
        BtnAddCompraMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddCompraMPActionPerformed(evt);
            }
        });
        jPanel23.add(BtnAddCompraMP);
        BtnAddCompraMP.setBounds(70, 40, 280, 50);

        btnSeleccionarIngrediente.setBackground(new java.awt.Color(204, 102, 0));
        btnSeleccionarIngrediente.setText("Seleccione Ingrediente");
        btnSeleccionarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarIngredienteActionPerformed(evt);
            }
        });
        jPanel23.add(btnSeleccionarIngrediente);
        btnSeleccionarIngrediente.setBounds(790, 100, 170, 35);

        txtNombreIngrediente.setBackground(new java.awt.Color(255, 204, 102));
        txtNombreIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreIngredienteActionPerformed(evt);
            }
        });
        jPanel23.add(txtNombreIngrediente);
        txtNombreIngrediente.setBounds(560, 100, 210, 28);

        txtNombreProveedorMP.setBackground(new java.awt.Color(255, 204, 102));
        txtNombreProveedorMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProveedorMPActionPerformed(evt);
            }
        });
        jPanel23.add(txtNombreProveedorMP);
        txtNombreProveedorMP.setBounds(110, 140, 190, 28);

        btnSeleccionarProveedorMP.setBackground(new java.awt.Color(204, 102, 0));
        btnSeleccionarProveedorMP.setText("Seleccionar");
        btnSeleccionarProveedorMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarProveedorMPMouseClicked(evt);
            }
        });
        btnSeleccionarProveedorMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProveedorMPActionPerformed(evt);
            }
        });
        jPanel23.add(btnSeleccionarProveedorMP);
        btnSeleccionarProveedorMP.setBounds(310, 140, 100, 30);
        jPanel23.add(jDateChooser1);
        jDateChooser1.setBounds(110, 170, 160, 30);

        btnVolver.setBackground(new java.awt.Color(204, 102, 0));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel23.add(btnVolver);
        btnVolver.setBounds(690, 160, 80, 30);

        jPanel19.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 970, 210));

        tablaComprasGenerales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaComprasGenerales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaComprasGeneralesMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaComprasGeneralesMouseClicked(evt);
            }
        });
        tablaComprasGenerales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaComprasGeneralesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaComprasGeneralesKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tablaComprasGenerales);

        jPanel19.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 970, 190));

        jPanel26.setBackground(new java.awt.Color(255, 204, 102));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel19.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 370, -1));

        btnVerDetalleCompraMP.setBackground(new java.awt.Color(204, 102, 0));
        btnVerDetalleCompraMP.setText("Ver Detalle Compra");
        btnVerDetalleCompraMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetalleCompraMPActionPerformed(evt);
            }
        });
        jPanel19.add(btnVerDetalleCompraMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 160, 40));

        jPanel29.setBackground(new java.awt.Color(255, 153, 51));
        jPanel29.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones Ingredientes Añadidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18))); // NOI18N
        jPanel29.setToolTipText("");
        jPanel29.setName(""); // NOI18N
        jPanel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel29MouseClicked(evt);
            }
        });
        jPanel29.setLayout(null);

        BtnModificarIngredienteFromCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconModify.png"))); // NOI18N
        BtnModificarIngredienteFromCompra.setText("Modificar Ingrediente");
        BtnModificarIngredienteFromCompra.setDefaultCapable(false);
        BtnModificarIngredienteFromCompra.setDescription(" ");
        BtnModificarIngredienteFromCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarIngredienteFromCompraActionPerformed(evt);
            }
        });
        jPanel29.add(BtnModificarIngredienteFromCompra);
        BtnModificarIngredienteFromCompra.setBounds(0, 40, 260, 50);

        BtnDeleteIngredienteFromCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconDelete.png"))); // NOI18N
        BtnDeleteIngredienteFromCompra.setText("Eliminar Ingrediente");
        BtnDeleteIngredienteFromCompra.setDescription(" ");
        BtnDeleteIngredienteFromCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteIngredienteFromCompraActionPerformed(evt);
            }
        });
        jPanel29.add(BtnDeleteIngredienteFromCompra);
        BtnDeleteIngredienteFromCompra.setBounds(260, 40, 250, 50);

        jPanel19.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 510, 110));

        jPanel25.setBackground(new java.awt.Color(255, 204, 102));
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Busqueda"));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchFieldCompra.setBackground(new java.awt.Color(255, 204, 102));
        searchFieldCompra.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        searchFieldCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchFieldCompra.setText("Ingrese su Busqueda");
        searchFieldCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldCompraMouseClicked(evt);
            }
        });
        searchFieldCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchFieldCompraKeyTyped(evt);
            }
        });
        jPanel25.add(searchFieldCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 190, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconSearch.png"))); // NOI18N
        jPanel25.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 30, 30));

        searchFilterCompra.setBackground(new java.awt.Color(255, 102, 102));
        searchFilterCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Fecha", "Nombre Proveedor" }));
        jPanel25.add(searchFilterCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, 30));

        jPanel19.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, 110));

        jPanel30.setBackground(new java.awt.Color(255, 153, 51));
        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones Compras Registradas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tempus Sans ITC", 1, 18))); // NOI18N
        jPanel30.setToolTipText("");
        jPanel30.setName(""); // NOI18N
        jPanel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel30MouseClicked(evt);
            }
        });
        jPanel30.setLayout(null);

        BtnModificarDatosCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconModify.png"))); // NOI18N
        BtnModificarDatosCompra.setText("Modificar Datos Compra");
        BtnModificarDatosCompra.setDefaultCapable(false);
        BtnModificarDatosCompra.setDescription(" ");
        BtnModificarDatosCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarDatosCompraActionPerformed(evt);
            }
        });
        jPanel30.add(BtnModificarDatosCompra);
        BtnModificarDatosCompra.setBounds(10, 30, 320, 40);

        BtnDeleteCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconDelete.png"))); // NOI18N
        BtnDeleteCompra.setText("Eliminar Compra");
        BtnDeleteCompra.setDescription(" ");
        BtnDeleteCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteCompraActionPerformed(evt);
            }
        });
        jPanel30.add(BtnDeleteCompra);
        BtnDeleteCompra.setBounds(330, 30, 230, 40);

        jPanel19.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 80));

        jPanel21.setBackground(new java.awt.Color(255, 204, 102));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 29)); // NOI18N
        jLabel20.setText("COMPRAS MATERIA PRIMA");
        jPanel21.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, 40));

        jPanel19.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 400, 60));

        javax.swing.GroupLayout panelComprasLayout = new javax.swing.GroupLayout(panelCompras);
        panelCompras.setLayout(panelComprasLayout);
        panelComprasLayout.setHorizontalGroup(
            panelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(panelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelComprasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelComprasLayout.setVerticalGroup(
            panelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(panelComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelComprasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDProveedorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProveedorCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProveedorCompraActionPerformed

    private void btnLimpiarCompraMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCompraMPActionPerformed
        limpiezaTotalCompra();
    }//GEN-LAST:event_btnLimpiarCompraMPActionPerformed

    private void txtIDCompraMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCompraMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCompraMPActionPerformed

    private void txtIDProductoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProductoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProductoCompraActionPerformed

    private void txtCantidadCompradaMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadCompradaMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadCompradaMPActionPerformed

    private void BtnAddMateriaPToCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddMateriaPToCompraActionPerformed

        agregarProductoaCompra();

        int ans = JOptionPane.showConfirmDialog(null,"¿Desea Agregar OTRO Producto a la Compra?","Pregunta",JOptionPane.YES_OPTION);
        if(ans == JOptionPane.YES_OPTION){
            limpiarProductoCompra();
            JOptionPane.showMessageDialog(null,"Agregue los Datos del Producto y Registrelo en la Compra","Confirmar",JOptionPane.WARNING_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null,"Compra Registrada con sus Productos en el Sistema","Confirmar",JOptionPane.WARNING_MESSAGE);
            limpiezaTotalCompra();
        }
    }//GEN-LAST:event_BtnAddMateriaPToCompraActionPerformed

    private void BtnAddCompraMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddCompraMPActionPerformed
        //CHECAR COMO CASTEAR DE STRING A DATE PARA PODER INSERTAR EN LA BASE DE DATOS LAS FECHAS :v
        //String stringFecha = txtFechaCompraMP.getText();
        String stringFecha = getFecha(jDateChooser1);
        Date fechaConvertida = null;
        java.sql.Date sqlDate = null;

        try {
            //Se necesita definir un formato para poder cambiar el String a Date
            //En este caso buscará en el String año-mes-dia hora:minutos:segundos

            //En este caso buscará en el String dia/mes/año
            DateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
            fechaConvertida = formatoFecha.parse(stringFecha);

            sqlDate = new java.sql.Date(fechaConvertida.getTime());

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        }

        try{
            int k = JOptionPane.showConfirmDialog(null,"¿Desea Registrar esta Compra?","Pregunta",JOptionPane.YES_OPTION);
            if(k == JOptionPane.YES_OPTION){
                CallableStatement cst = con.conectar().prepareCall("{call insertarDatos_CompraMateriaP(?,?,?)}");
                //Paramteros del procedimiento
                cst.setString(1,txtIDCompraMP.getText().toUpperCase());
                cst.setString(2,txtIDProveedorCompra.getText().toUpperCase());
                cst.setDate(3,sqlDate);
                //Ejecurar el PreparedStatment.... se hace con ResultSet
                cst.execute();
                cst.close();

                cargarComprasGenerales();
                JOptionPane.showMessageDialog(null,"Compra Registrada Correctamente, REGISTRE LOS PRODUCTOS DE SU COMPRA","Confirmar",JOptionPane.WARNING_MESSAGE);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnAddCompraMPActionPerformed

    private void btnSeleccionarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarIngredienteActionPerformed
        SeleccionarMateriaPrimaCompra objSeleccionar = new SeleccionarMateriaPrimaCompra();
        objSeleccionar.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarIngredienteActionPerformed

    private void txtNombreIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreIngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreIngredienteActionPerformed

    private void txtNombreProveedorMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProveedorMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProveedorMPActionPerformed

    private void btnSeleccionarProveedorMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProveedorMPActionPerformed
        SeleccionarProveedorMateriaP objProveedorMP = new SeleccionarProveedorMateriaP();
        objProveedorMP.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarProveedorMPActionPerformed

    private void jPanel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel23MouseClicked

    private void tablaComprasGeneralesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaComprasGeneralesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaComprasGeneralesMouseClicked

    private void tablaComprasGeneralesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaComprasGeneralesMousePressed
        txtIDCompraMP.setEnabled(false);
        txtNombreProveedorMP.setEnabled(false);

        //Metodo para mostrar los valores de la JTable en los Campos de Texto
        //1.- Guardar en una variable entero la fila que se selecciona
        int fila = this.tablaComprasGenerales.getSelectedRow();

        String index;
        String idCompra = tablaComprasGenerales.getValueAt(fila, 1).toString();
        //Codigo para settear los datos en los campos de texto
        this.txtIDCompraMP.setText(idCompra);
        this.txtNombreProveedorMP.setText(tablaComprasGenerales.getValueAt(fila,2).toString());
        this.txtFechaCompraMP.setText(tablaComprasGenerales.getValueAt(fila,3).toString());
        try{
            String fecha = txtFechaCompraMP.getText();
            Date fechaParseada= new SimpleDateFormat("yyyy-MM-dd").parse(fecha);
            jDateChooser1.setDate(fechaParseada);
        }
        catch(ParseException ex){
            JOptionPane.showMessageDialog(this,"NO se pudo conseguir la fecha");
        }

    }//GEN-LAST:event_tablaComprasGeneralesMousePressed

    private void tablaComprasGeneralesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaComprasGeneralesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaComprasGeneralesKeyPressed

    private void btnVerDetalleCompraMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetalleCompraMPActionPerformed
        if(txtIDCompraMP.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Seleccione una Compra de la Tabla","Confirmar",JOptionPane.WARNING_MESSAGE);
        }else{
            VerDetalleCompraMP1 objVerDetalleCompraMP = new VerDetalleCompraMP1();
            VerDetalleCompraMP1.txtIDCompraDetalle.setText(txtIDCompraMP.getText());
            objVerDetalleCompraMP.setVisible(true);
        }

    }//GEN-LAST:event_btnVerDetalleCompraMPActionPerformed

    private void BtnModificarIngredienteFromCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarIngredienteFromCompraActionPerformed
        if(txtNombreIngrediente.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Seleccione un producto del detalle de la compra para ser modificado","Aviso",JOptionPane.WARNING_MESSAGE);
        }else{
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas modificar los datos del producto en la compra?","Confirmar",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            //Seleccionar Si devuelve 0
            //Seleccionar No devuelve 1
            //Seleccionar Cancelar devuelve 2
            if(confirmacion == JOptionPane.YES_OPTION){
                //En este caso buscará en el String dia/mes/año
                //String stringFecha = txtCaducidadIngrediente.getText();
                String stringFecha = getFecha(jDateChooser1);
                Date fechaConvertida = null;
                java.sql.Date sqlDate = null;
                try {
                    //Se necesita definir un formato para poder cambiar el String a Date
                    //En este caso buscará en el String año-mes-dia hora:minutos:segundos

                    //En este caso buscará en el String dia/mes/año
                    DateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                    fechaConvertida = formatoFecha.parse(stringFecha);

                    sqlDate = new java.sql.Date(fechaConvertida.getTime());

                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null,e.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
                }

                try{

                    CallableStatement cst = con.conectar().prepareCall("{call modificarDetalle_CompraMP(?,?,?,?)}");
                    //Paramteros del procedimiento
                    cst.setString(1,txtIDCompraMP.getText().toUpperCase());
                    cst.setString(2,txtIDProductoCompra.getText().toUpperCase());
                    cst.setInt(3,Integer.parseInt(txtCantidadCompradaMP.getText()));
                    cst.setDate(4,sqlDate);

                    cst.execute();
                    cst.close();
                    //Actualizar la JTable
                    cargarComprasGenerales();
                    limpiarProductoCompra();
                    JOptionPane.showMessageDialog(null,"Datos del Producto Modificado en la Compra Correctamente","Notificacion",JOptionPane.WARNING_MESSAGE);
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,e.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
                }
            }
            else{
                limpiarProductoCompra();
                JOptionPane.showMessageDialog(null,"Has cancelado la Modificacion","Aviso",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnModificarIngredienteFromCompraActionPerformed

    private void BtnDeleteIngredienteFromCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteIngredienteFromCompraActionPerformed
        if(txtNombreIngrediente.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Seleccione un producto del detalle de la compra para ser eliminado","Aviso",JOptionPane.WARNING_MESSAGE);
        }else{
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas eliminar los datos del producto en la compra?","Confirmar Eliminacion",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            //Seleccionar Si devuelve 0
            //Seleccionar No devuelve 1
            //Seleccionar Cancelar devuelve 2
            if(confirmacion == JOptionPane.YES_OPTION){
                try{
                    CallableStatement cst = con.conectar().prepareCall("{call eliminarDetalle_CompraMP(?,?,?)}");
                    //Paramteros del procedimiento
                    cst.setString(1,txtIDCompraMP.getText().toUpperCase());
                    cst.setString(2,txtIDProductoCompra.getText().toUpperCase());
                    cst.setInt(3,Integer.parseInt(txtCantidadCompradaMP.getText()));

                    cst.execute();
                    cst.close();
                    //Actualizar la JTable
                    cargarComprasGenerales();
                    limpiarProductoCompra();
                    JOptionPane.showMessageDialog(null,"Datos del Producto Eliminados en la Compra Correctamente","Notificacion",JOptionPane.WARNING_MESSAGE);
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,e.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
                }
            }
            else{
                limpiarProductoCompra();
                JOptionPane.showMessageDialog(null,"Has cancelado la eliminacion","Aviso",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnDeleteIngredienteFromCompraActionPerformed

    private void jPanel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel29MouseClicked

    private void searchFieldCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldCompraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldCompraMouseClicked

    private void searchFieldCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldCompraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldCompraKeyTyped

    private void BtnModificarDatosCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarDatosCompraActionPerformed
        if(txtIDCompraMP.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Seleccione una compra de la tabla para ser modificada","Aviso",JOptionPane.WARNING_MESSAGE);
        }else{
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Seguro que deseas modificar los datos de la compra?","Confirmar",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            //Seleccionar Si devuelve 0
            //Seleccionar No devuelve 1
            //Seleccionar Cancelar devuelve 2
            if(confirmacion == JOptionPane.YES_OPTION){

                //En este caso buscará en el String dia/mes/año
                //String stringFecha = txtFechaCompraMP.getText();
                String stringFecha = getFecha(jDateChooser1);
                Date fechaConvertida = null;
                java.sql.Date sqlDate = null;
                try {
                    //Se necesita definir un formato para poder cambiar el String a Date
                    //En este caso buscará en el String año-mes-dia hora:minutos:segundos

                    //En este caso buscará en el String dia/mes/año
                    DateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                    fechaConvertida = formatoFecha.parse(stringFecha);

                    sqlDate = new java.sql.Date(fechaConvertida.getTime());

                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null,e.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
                }

                try{

                    CallableStatement cst = con.conectar().prepareCall("{call modificarDatos_CompraMP(?,?,?)}");
                    //Paramteros del procedimiento
                    cst.setString(1,txtIDCompraMP.getText().toUpperCase());
                    cst.setString(2,txtIDProveedorCompra.getText().toUpperCase());
                    cst.setDate(3,sqlDate);

                    cst.execute();
                    cst.close();
                    //Actualizar la JTable
                    cargarComprasGenerales();
                    limpiezaTotalCompra();
                    JOptionPane.showMessageDialog(null,"Datos de la Compra Modificados Correctamente","Notificacion",JOptionPane.WARNING_MESSAGE);
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,e.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
                }
            }
            else{
                limpiezaTotalCompra();
                JOptionPane.showMessageDialog(null,"Has cancelado la Modificacion","Aviso",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnModificarDatosCompraActionPerformed

    private void BtnDeleteCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDeleteCompraActionPerformed

    private void jPanel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel30MouseClicked

    private void jPanel19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel19MousePressed

    private void btnSeleccionarProveedorMPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarProveedorMPMouseClicked
        //JOptionPane.showMessageDialog(this,getFecha(jDateChooser1));
    }//GEN-LAST:event_btnSeleccionarProveedorMPMouseClicked

    private void tablaComprasGeneralesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaComprasGeneralesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaComprasGeneralesKeyReleased

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Principal obj = new Principal();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtFechaCompraMPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaCompraMPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaCompraMPKeyReleased

    private void txtFechaCompraMPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaCompraMPFocusGained
        txtFechaCompraMP.setText("");
    }//GEN-LAST:event_txtFechaCompraMPFocusGained

    private void txtCantidadCompradaMPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadCompradaMPKeyTyped
        String cara= String.valueOf(evt.getKeyChar());
        String nombrePattern="[\\d]";
        String cad;
        Pattern pattern = Pattern.compile(nombrePattern);
        Matcher matcher = pattern.matcher(cara);
        if(matcher.matches()==false){
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadCompradaMPKeyTyped

    private void txtIDCompraMPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDCompraMPKeyTyped
         if(txtIDCompraMP.getText().length()<3){
            txtIDCompraMP.setText("CMP");
        }
        if(txtIDCompraMP.getText().length()>=6){
            evt.consume();
        }
        String cara= String.valueOf(evt.getKeyChar());
        String nombrePattern="[\\d]";
        String cad;
        Pattern pattern = Pattern.compile(nombrePattern);
        Matcher matcher = pattern.matcher(cara);
        if(matcher.matches()==false){
            evt.consume();
        }
        else{
            cad=txtIDCompraMP.getText();
            if(cad.length()>=3&&cad.length()<=6){
                if(cad.length()!=3){
                    nombrePattern="^[CMP]+[\\d]{1,3}";
                    pattern = Pattern.compile(nombrePattern);
                    matcher = pattern.matcher(cad)  ;
                    if(matcher.matches()==false){evt.consume();}
                }
            }
            else{evt.consume();}
        }
    }//GEN-LAST:event_txtIDCompraMPKeyTyped

    public void limpiezaTotalCompra(){
        txtIDCompraMP.setText("CMP");
        txtIDProveedorCompra.setText("");
        txtFechaCompraMP.setText("aaaa/MM/dd");
        txtNombreProveedorMP.setText("");
        jDateChooser1.setCalendar(null);
        
        txtIDCompraMP.setEnabled(true);
        limpiarProductoCompra();
    }
    
    public void agregarProductoaCompra(){
        //CHECAR COMO CASTEAR DE STRING A DATE PARA PODER INSERTAR EN LA BASE DE DATOS LAS FECHAS :v
        
        /*String stringFecha = txtCaducidadIngrediente.getText();
        Date fechaConvertida = null;
        java.sql.Date sqlDate = null;
        
        try {
            //Se necesita definir un formato para poder cambiar el String a Date
            //En este caso buscará en el String año-mes-dia hora:minutos:segundos

            //En este caso buscará en el String dia/mes/año
            DateFormat formatoFecha = new SimpleDateFormat("yyyy/MM/dd");
            fechaConvertida = formatoFecha.parse(stringFecha);
            
            sqlDate = new java.sql.Date(fechaConvertida.getTime());
            

        } catch (ParseException e) {
            System.out.println("Error: " + e.getMessage());
	    }
        */

        try{
            int k = JOptionPane.showConfirmDialog(null,"¿Desea Agregar este Producto a la Compra?","Pregunta",JOptionPane.YES_OPTION);
            if(k == JOptionPane.YES_OPTION){
                CallableStatement cst = con.conectar().prepareCall("{call insertarDetalle_CompraMP(?,?,?)}");
                //Paramteros del procedimiento
                cst.setString(1,txtIDCompraMP.getText().toUpperCase());
                cst.setString(2,txtIDProductoCompra.getText().toUpperCase());
                cst.setInt(3,Integer.parseInt(txtCantidadCompradaMP.getText()));
               // cst.setDate(4,sqlDate);
                //Ejecurar el PreparedStatment.... se hace con ResultSet
                cst.execute();
                cst.close();

                JOptionPane.showMessageDialog(null,"Producto Registrado en la Compra Correctamente","Confirmar",JOptionPane.WARNING_MESSAGE);   
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
        }
        cargarComprasGenerales();
    }//Cierre metodo agregarProductoaCompra
    
    public void limpiarProductoCompra(){
        txtNombreIngrediente.setText("");
        txtIDProductoCompra.setText("");
        txtCantidadCompradaMP.setText("");
        //txtCaducidadIngrediente.setText("aaaa/MM/dd");
    }
    
    public void cargarComprasGenerales(){
        try{
            //PREPARAR LA jTable
            String titulos[] = {"N°","ID Compra","Id Proveedor","Fecha","Total"}; //Se definen los titulos que tendra la tabla
            comprasTableModel = new DefaultTableModel(null,titulos); //Se cargan los titulos a la tabla
            String fila [] = new String[5]; //Se define el tamaño de columnas que tendra cada fila en la que se cargaran los datos

            //Crear un objeto de JTable para aplicar los hacks de ordenar :v
            JTable p = new JTable(comprasTableModel);

            //PREPARAR LA CONEXION A SQL Y EL OBJETO PARA EJECUTAR LA CONSULTA DE LA VISTA :v
            Statement smt=con.conectar().createStatement(); //Crea un objeto para poder hacer la consultar con ResultSet
            String consulta = "Select * from verComprasMP";
            ResultSet r = smt.executeQuery(consulta); //Es el equivalente a la wea que devuelve el metodo listar() :v
            //Empezar a cargar los datos---
            int c = 1;
            while(r.next()){
                fila[0] = String.valueOf(c) + "°";
                //A partir de aqui empieza a cargar los datos de la base de datos ala jTable
                fila[1] = r.getString(1);
                fila[2] = r.getString(2);
                fila[3] = r.getString(3);
                fila[4] = r.getString(4);
                comprasTableModel.addRow(fila); //Con este codigo agrega toda una fila de datos, la cual representa los datos de un docente
                c++;
            }
            r.close();

            tablaComprasGenerales.setModel(comprasTableModel); //Carga el modelo a la tabla que se definio anteriormente
            //Weas que ordenan :v
            TableRowSorter<TableModel> ordena = new TableRowSorter<TableModel>(comprasTableModel);
            tablaComprasGenerales.setRowSorter(ordena);
            this.tablaComprasGenerales.setModel(comprasTableModel);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error al cargar los datos a la tabla: "+e.getMessage(),"ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
        }
    }//Cierre cargarComprasGenerales
    
    public void formatojTableDatosGeneralesCompras(){
        tablaComprasGenerales.getColumnModel().getColumn(0).setPreferredWidth(1); //Numeracion
        tablaComprasGenerales.getColumnModel().getColumn(1).setPreferredWidth(6);
        tablaComprasGenerales.getColumnModel().getColumn(2).setPreferredWidth(6);
        tablaComprasGenerales.getColumnModel().getColumn(3).setPreferredWidth(15);
        tablaComprasGenerales.getColumnModel().getColumn(4).setPreferredWidth(15);
    }//Cierre metodo formatojTableDatosGeneralesCompras
    
    public String getFecha(JDateChooser jd){
        /*
        * Para mandar a llamar el metodo el parametro que recibe
        * es el nombre del componente(jDateChooser)
        * y retorna un string.
        */
        if (jd.getDate()!=null){
            return Formato.format(jd.getDate());
        }else{
          return "Ingrese fecha";
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprasMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprasMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprasMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprasMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprasMateriaPrima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask BtnAddCompraMP;
    private org.edisoncor.gui.button.ButtonTask BtnAddMateriaPToCompra;
    private org.edisoncor.gui.button.ButtonTask BtnDeleteCompra;
    private org.edisoncor.gui.button.ButtonTask BtnDeleteIngredienteFromCompra;
    private org.edisoncor.gui.button.ButtonTask BtnModificarDatosCompra;
    private org.edisoncor.gui.button.ButtonTask BtnModificarIngredienteFromCompra;
    private org.edisoncor.gui.button.ButtonColoredAction btnLimpiarCompraMP;
    private org.edisoncor.gui.button.ButtonColoredAction btnSeleccionarIngrediente;
    private org.edisoncor.gui.button.ButtonColoredAction btnSeleccionarProveedorMP;
    private org.edisoncor.gui.button.ButtonColoredAction btnVerDetalleCompraMP;
    private org.edisoncor.gui.button.ButtonColoredAction btnVolver;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JScrollPane jScrollPane4;
    private jcMousePanel.jcMousePanel panelCompras;
    private javax.swing.JTextField searchFieldCompra;
    private javax.swing.JComboBox<String> searchFilterCompra;
    private javax.swing.JTable tablaComprasGenerales;
    public static javax.swing.JTextField txtCantidadCompradaMP;
    private javax.swing.JTextField txtFechaCompraMP;
    private javax.swing.JTextField txtIDCompraMP;
    public static javax.swing.JTextField txtIDProductoCompra;
    public static javax.swing.JTextField txtIDProveedorCompra;
    public static javax.swing.JTextField txtNombreIngrediente;
    public static javax.swing.JTextField txtNombreProveedorMP;
    // End of variables declaration//GEN-END:variables
}
